version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE" 
      TYPE: "FORGE"
      VERSION: "1.20.1"
      MEMORY: "4G"
      ONLINE_MODE: "FALSE" 
      ENABLE_RCON: "true"
      RCON_PASSWORD: "1123"
    volumes:
      - ./minecraft-data:/data
      - ./mods:/data/mods
    restart: unless-stopped
